language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install: npm install
script: bash ./docs/deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "be0b3b658a36"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"

