language: node_js
cache:
  directories:
    - node_modules
install: npm install
jobs:
  include:
    - stage: test
      node_js:
        - "6"
        - "7"
      script: bash ./deploy/test.sh
    - stage: build
      node_js: "6"
      script: bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "af862fa96d3e"
    - COMMIT_AUTHOR_EMAIL: "amishshah.2k@gmail.com"
dist: trusty
sudo: false
