name: 'Issue Labeler'
on:
  issues:
    types: [opened, edited]

jobs:
  issue-triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v2.5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/issue-labeler.yml
          not-before: 2022-11-27T07:05:06.752Z
          enable-versioned-regex: 0
