name: Lint

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/setup-node@master
      with:
        node-version: 12
      run: npm install
    - name: eslint
      if: github.event_name == 'pull_request'
      uses: ./.github/actions/eslint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: eslint
      if: github.event_name == 'push'
      run: npm run lint
    - name: lint typings
      run: npm run lint:typings
    - name: lint docs
      run: npm run docs:test
