name: 'Stale PR'
on:
  schedule:
    - cron: '0 16 * * *'
permissions:
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: ''
          stale-pr-label: 'stale'
          days-before-stale: 90
          days-before-close: 7
          exempt-pr-labels: 'blocked'
